### ISSUE TITLE
Images for cocktail now displaying.  http/https issue?

### ISSUE THREAD

**Issue by hykgoml** [mykle1/MMM-Cocktails#10]
Installed and got the feeds (text) woriking. What does not work is the images.
Using Shift-Alt-I I see the module is looking for an image file that is not there.
Example:
Broken (as not displayed in the Mirror)
http://https//www.thecocktaildb.com/images/media/drink/0fbo2t1485620752.jpg
So it seems to be getting redirected to the https site, but has already padded the URL with HTTP…

Correct URL:
https://www.thecocktaildb.com/images/media/drink/0fbo2t1485620752.jpg

The website seems to have updated their API to support HTTPS :
https://www.thecocktaildb.com/api.php
IDK, I assume because of google? ( https://www.theverge.com/2018/2/8/16991254/chrome-not-secure-marked-http-encryption-ssl )

So I think I get the issue, I just don’t know how to fix…

**Comment by mykle1** [comment]
Thanks for bringing that to my attention. Get the update and it should work as expected now. I tested it for an hour without incident.
