### ISSUE TITLE
wont load through MMM-Carousel

### ISSUE THREAD

**Issue by mirror-master** [mykle1/MMM-Cocktails#2]
Awesome module, but like other modules, i cannot get it to load on any slide other than slide 1 using MMM-Carousel.   It stays on the message "mixing your drink"

**Comment by mykle1** [comment]
Sorry for the late response. I don't check in here very often and this is my first and oldest module. Didn't think anyone was actually using it, so thanks for your interest. I'm sorry it's not working in conjunction with MMM-Carousel. I don't use it that myself but I'll look into the reason. However, if you want to take a shot at it, you are more than welcome to. Again, thanks for your interest in my module

**Comment by mykle1** [comment]
Contact me at the forum in the future, if need be. It is only by chance that I stopped in here and saw your comments
